# Configuração do arquivo render.yaml para o projeto da Imobiliaria

services:
  # Serviço do Gateway Nginx
  - type: web
    plan: free
    runtime: docker
    name: gateway
    repo: https://github.com/InteliJR/Imobiliaria 
    rootDir: ./src/Gateway
    dockerfilePath: ./src/Gateway/Dockerfile
    envVars:
      - fromGroup: production-env # Carrega as variáveis comuns do grupo
    scaling:
      minInstances: 1
      maxInstances: 2

  # Serviço de autenticação (auth-service)
  - type: web
    plan: free
    runtime: docker
    name: auth-service
    repo: https://github.com/InteliJR/Imobiliaria 
    rootDir: ./src/Auth-service/
    dockerfilePath: ./src/Auth-service/Dockerfile
    envVars:
      - fromGroup: production-env
    scaling:
      minInstances: 1
      maxInstances: 3

  # Banco de Dados MongoDB
  - type: pserv
    plan: free
    runtime: docker
    name: mongodb
    repo: https://github.com/InteliJR/Imobiliaria 
    dockerfilePath: ./src/logging-mongodb/Dockerfile
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: Imobiliaria
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: C4c42024
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 1

# Grupos de variáveis de ambiente
envVarGroups:
  - name: production-env
    envVars:
      # Configurações do banco de dados
      - key: ConnectionStrings__DefaultConnection
        value: User Id=maricarmosan01;Password=N8ebCmZg2l8emJj6V71PfsCVMOJm7cLk;Server=dpg-csce4p08fa8c73fv6b00-a.virginia-postgres.render.com;Port=5432;Database=imobiliaria_database;Pooling=true;MinPoolSize=5;MaxPoolSize=100;KeepAlive=30;CommandTimeout=60;
      
      # Configurações do MongoDB
      - key: MONGO_CONNECTION_STRING
        value: mongodb://Imobiliaria:C4c42024@mongodb:27017/?authSource=admin
      - key: MONGO_DATABASE_NAME
        value: AuthServiceDb
      - key: MONGO_LOGS_COLLECTION_NAME
        value: Logs
      
      # Configurações do JWT
      - key: JwtSettings__SecretKey
        value: da/PtLNn1uz22BIZKKYxlRpYZDQx5BmE7PYB9Yu+HOs=
      - key: JwtSettings__ExpiryMinutes
        value: "60"
      - key: JwtSettings__Issuer
        value: AuthService
      - key: JwtSettings__Audience
        value: Services

