version: '3.8'

services:
  auth-service:
    build:
      context: ./Auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - ./Auth-service/Layer.Application/.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
