services:
  auth-service:
    build:
      context: ./Auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - ./Auth-service/Layer.Application/.env.production
    networks:
      - app-network
  property-service:
    build:
      context: ./Property-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
    env_file:
      - ./Property-service/Layer.Application/.env.production
    networks:
      - app-network
  payment-service:
    build:
      context: ./Payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8082
    env_file:
      - ./Payment-service/Layer.Application/.env
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "83:80"
    networks:
      - app-network
    depends_on:
      - auth-service
  gateway:
    build: 
      context: ./Gateway
      dockerfile: DockerfileDev
    ports:
      - "8093:8093"
      - "8094:8094"
    depends_on:
      - auth-service
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge
